project:
  type: website
  output-dir: docs

website:
  title: "Ademco Vista Series"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:introduction

sidebar:
  - id: introduction
    title: "Introduction"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - introduction.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
