project:
  type: website
  output-dir: docs

website:
  title: "Ademco Vista Series"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: introduction.qmd

sidebar:
  - title: "Introduction"
    style: "docked"
    background: light
    contents:
      - introduction.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
