project:
  type: website
  output-dir: docs

website:
  title: "Ademco Vista Series"
  navbar:
    background: primary
    search: true
    left:
      - sidebar:home

sidebar:
  - id: home
    title: "Home"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - index.qmd
      - introduction.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
