project:
  type: website
  output-dir: docs

website:
  title: "Ademco Vista Series"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

sidebar:
  - title: "Home"
    style: "docked"
    background: light
    contents:
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
